create table member (
                        member_id bigint generated by default as identity  comment "회원번호",
                        name varchar(255) not null comment "이름",
                        birth varchar(255) not null comment "생년월일",
                        email varchar(255) comment "이메일",
                        phone_num varchar(255) not null comment "휴대폰번호",
                        user_ci varchar(255),
                        user_seq_no varchar(255) not null comment "사용자일련번호",
                        primary key (member_id)
);

create table daily_settlement (
                        settlement_istt_cd varchar(255) not null comment "정산기관코드",
                        settlement_dt timestamp not null comment "정산일자",
                        withdrawal_amt varchar(255) not null comment "출금금액",
                        deposit_amt varchar(255) not null comment "입금금액",
                        total_amt varchar(255) not null comment "합산금액",
                        error_cd varchar(255) comment "오류코드",
                        error_msg varchar(255) comment "오류메세지",
                        operate_dt timestamp not null comment "조작일시",
                        primary key (settlement_istt_cd, settlement_dt)
);


create table opbk_usng_acnt (
                                register_account_num varchar(255) not null comment "등록계좌번호",
                                register_bank_code_std varchar(255) not null comment "등록계좌개설기관 표준코드(3글자)",
                                register_account_seq varchar(255) comment "등록계좌상품회차(예금)",
                                account_type varchar(255) comment "등록계좌종류",
                                api_tran_dt timestamp not null comment "거래일시",
                                api_tran_id varchar(255) not null comment "api거래고유번호",
                                fintech_use_num varchar(255) comment "핀테크이용번호",
                                user_seq_no varchar(255) not null comment "사용자일련번호",
                                account_no bigint not null comment "당사계좌번호",
                                member_id bigint not null comment "회원번호",
                                delete_dvsn_cd varchar(255) not null comment "등록해지구분코드",
                                transfer_agree_yn varchar(255) comment "출금동의여부",
                                agmt_data_type varchar(255) comment "출금동의자료구분",
                                inquiry_agree_yn varchar(255) comment "조회동의여부",
                                payer_num varchar(255) not null comment "납부자번호",
                                error_cd varchar(255) comment "오류코드",
                                error_msg varchar(255) comment "오류메세지",
                                operate_dt timestamp not null comment "조작일시",
                                primary key (register_account_num, register_bank_code_std, user_seq_no)
);


create table opbk_tran_hist (
                                history_id bigint generated by default as identity,
                                api_tran_dt timestamp not null comment "거래일자",
                                api_tran_id varchar(255) not null comment "(요청기관)은행거래고유번호",
                                send_receive_cd varchar(255) not null comment "송수신구분코드",
                                inout_type varchar(255) not null comment "입출금구분코드",
                                req_client_bank_cd varchar(255) not null comment "요청고객계좌개설기관표준코드(3자리)",
                                req_client_name varchar(255) comment "요청고객성명",
                                fintech_use_num varchar(255) comment "요청고객핀테크번호",
                                tran_amt varchar(255) not null comment "거래금액",
                                tran_no varchar(255) not null comment "거래발생순번",
                                tran_purpose varchar(255) comment "이체용도",
                                wd_bank_code_std varchar(255) not null comment "출금은행코드",
                                wd_bank_code_sub varchar(255) not null comment "출금은행점별코드",
                                wd_bank_name varchar(255) not null comment "출금은행명",
                                wd_account_no varchar(255) not null comment "출금계좌번호",
                                wd_account_holder_name varchar(255) not null comment "송금인명",
                                wd_print_content varchar(255) comment "출금통장기재내용",
                                bank_code_std varchar(255) not null comment "입금은행코드",
                                savings_bank_name varchar(255) comment "개별저축은행명",
                                bank_code_sub varchar(255) not null comment "입금은행점별코드",
                                bank_name varchar(255) not null comment "입금은행이름",
                                account_no varchar(255) not null comment "입금계좌번호",
                                account_holder_name varchar(255) not null comment "입금계좌고객성명",
                                print_content varchar(255) comment "입금통장기재내용",
                                member_id bigint not null comment "요청고객회원번호",
                                error_cd varchar(255) comment "오류코드",
                                error_msg varchar(255) comment "오류메세지",
                                operate_dt timestamp not null comment "조작일시",
                                primary key (history_id)
);

create table own_acnt (
                          account_no varchar(255) not null,
                          account_type varchar(255)  not null,
                          member_id bigint  not null,
                          deposit bigint  not null,
                          institute_code varchar(255),
                          is_delete varchar(255),
                          enroll_time timestamp,
                          update_deposit_time timestamp,
                          primary key (account_no)
);

alter table opbk_usng_acnt
    add constraint FKiaogy1kgn4qi4p1k6igh1a3nj
        foreign key (account_no)
            references own_acnt;

alter table opbk_usng_acnt
    add constraint FK3hta15obqexrvm9ihov7flpfj
        foreign key (member_id)
            references member;

alter table opbn_tran_hist
    add constraint FK9qg7oifyjaap01kh7ts6ll1ku
        foreign key (member_id)
            references member;


alter table own_acnt
    add constraint FKry3h7jb4fnsv0pjx9d6b8t6w
        foreign key (member_id)
            references member;